### ISSUE TITLE
yum update broken?

### ISSUE THREAD

**Issue by futureweb** [iusrepo/mariadb102#3]
Hey there,
I got a CentOS Linux release 7.6.1810 (Core) installation with mariadb102 - today I tried a "yum update" but it fails with dependencie Errors for mariadb-libs?

Any ideas on that? thx, bye from Austria
Andreas

> CT-412 /# rpm -qa | grep -i mariadb                   
> mariadb102-backup-10.2.24-1.el7.ius.x86_64
> mariadb102-common-10.2.24-1.el7.ius.x86_64
> mariadb102-libs-10.2.24-1.el7.ius.x86_64
> mariadb102-10.2.24-1.el7.ius.x86_64
> mariadb102-server-10.2.24-1.el7.ius.x86_64
> mariadb102-devel-10.2.24-1.el7.ius.x86_64
> mariadb102-oqgraph-engine-10.2.24-1.el7.ius.x86_64
> mariadb-libs-5.5.60-1.el7_5.x86_64
> mariadb102-errmsg-10.2.24-1.el7.ius.x86_64
> mariadb102-server-utils-10.2.24-1.el7.ius.x86_64

> CT-412 /# yum update --exclude=mariadb-libs          
> Loaded plugins: fastestmirror, protectbase, replace
> Loading mirror speeds from cached hostfile
>  * base: mirror.nextlayer.at
>  * epel: mirror.nextlayer.at
>  * extras: mirror.nextlayer.at
>  * updates: mirror.nextlayer.at
> 0 packages excluded due to repository protections
> Resolving Dependencies
> --> Running transaction check
> ---> Package MariaDB-compat.x86_64 0:10.2.25-1.el7.centos will be obsoleting
> --> Processing Dependency: MariaDB-common for package: MariaDB-compat-10.2.25-1.el7.centos.x86_64
> ---> Package certbot.noarch 0:0.34.2-3.el7 will be updated
> ---> Package certbot.noarch 0:0.35.1-1.el7 will be an update
> ---> Package device-mapper.x86_64 7:1.02.149-10.el7_6.7 will be updated
> ---> Package device-mapper.x86_64 7:1.02.149-10.el7_6.8 will be an update
> ---> Package device-mapper-libs.x86_64 7:1.02.149-10.el7_6.7 will be updated
> ---> Package device-mapper-libs.x86_64 7:1.02.149-10.el7_6.8 will be an update
> ---> Package glibc.x86_64 0:2.17-260.el7_6.5 will be updated
> ---> Package glibc.x86_64 0:2.17-260.el7_6.6 will be an update
> ---> Package glibc-common.x86_64 0:2.17-260.el7_6.5 will be updated
> ---> Package glibc-common.x86_64 0:2.17-260.el7_6.6 will be an update
> ---> Package glibc-devel.x86_64 0:2.17-260.el7_6.5 will be updated
> ---> Package glibc-devel.x86_64 0:2.17-260.el7_6.6 will be an update
> ---> Package glibc-headers.x86_64 0:2.17-260.el7_6.5 will be updated
> ---> Package glibc-headers.x86_64 0:2.17-260.el7_6.6 will be an update
> ---> Package mariadb-libs.x86_64 1:5.5.60-1.el7_5 will be obsoleted
> --> Processing Dependency: mariadb-libs(x86-64) < 1:10 for package: 3:mariadb102-server-10.2.24-1.el7.ius.x86_64
> --> Processing Dependency: mariadb-libs(x86-64) < 1:10 for package: 3:mariadb102-common-10.2.24-1.el7.ius.x86_64
> ---> Package nscd.x86_64 0:2.17-260.el7_6.5 will be updated
> ---> Package nscd.x86_64 0:2.17-260.el7_6.6 will be an update
> ---> Package php73-bcmath.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-bcmath.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-cli.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-cli.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-common.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-common.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-dba.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-dba.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-devel.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-devel.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-fpm.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-fpm.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-fpm-httpd.noarch 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-fpm-httpd.noarch 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-gd.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-gd.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-imap.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-imap.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-intl.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-intl.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-json.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-json.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-mbstring.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-mbstring.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-mysqlnd.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-mysqlnd.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-odbc.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-odbc.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-opcache.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-opcache.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-pdo.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-pdo.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-process.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-process.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-pspell.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-pspell.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-tidy.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-tidy.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package php73-xml.x86_64 0:7.3.6-2.el7.ius will be updated
> ---> Package php73-xml.x86_64 0:7.3.7-1.el7.ius will be an update
> ---> Package python2-acme.noarch 0:0.34.2-1.el7 will be updated
> ---> Package python2-acme.noarch 0:0.35.1-1.el7 will be an update
> ---> Package python2-certbot.noarch 0:0.34.2-3.el7 will be updated
> ---> Package python2-certbot.noarch 0:0.35.1-1.el7 will be an update
> ---> Package python2-certbot-apache.noarch 0:0.34.2-1.el7 will be updated
> ---> Package python2-certbot-apache.noarch 0:0.35.1-1.el7 will be an update
> ---> Package python2-josepy.noarch 0:1.1.0-1.el7 will be updated
> ---> Package python2-josepy.noarch 0:1.2.0-1.el7 will be an update
> ---> Package systemd.x86_64 0:219-62.el7_6.6 will be updated
> ---> Package systemd.x86_64 0:219-62.el7_6.7 will be an update
> ---> Package systemd-libs.x86_64 0:219-62.el7_6.6 will be updated
> ---> Package systemd-libs.x86_64 0:219-62.el7_6.7 will be an update
> ---> Package systemd-sysv.x86_64 0:219-62.el7_6.6 will be updated
> ---> Package systemd-sysv.x86_64 0:219-62.el7_6.7 will be an update
> ---> Package tzdata.noarch 0:2019a-1.el7 will be updated
> ---> Package tzdata.noarch 0:2019b-1.el7 will be an update
> --> Running transaction check
> ---> Package MariaDB-common.x86_64 0:10.2.25-1.el7.centos will be installed
> ---> Package mariadb-libs.x86_64 1:5.5.60-1.el7_5 will be obsoleted
> --> Processing Dependency: mariadb-libs(x86-64) < 1:10 for package: 3:mariadb102-server-10.2.24-1.el7.ius.x86_64
> --> Processing Dependency: mariadb-libs(x86-64) < 1:10 for package: 3:mariadb102-common-10.2.24-1.el7.ius.x86_64
> --> Finished Dependency Resolution
> Error: Package: 3:mariadb102-server-10.2.24-1.el7.ius.x86_64 (@ius)
>            Requires: mariadb-libs(x86-64) < 1:10
>            Removing: 1:mariadb-libs-5.5.60-1.el7_5.x86_64 (@base)
>                mariadb-libs(x86-64) = 1:5.5.60-1.el7_5
>            Obsoleted By: MariaDB-compat-10.2.25-1.el7.centos.x86_64 (mariadb-main)
>                mariadb-libs(x86-64) = 1:10.1.38-1.el7.centos
>            Available: MariaDB-compat-10.2.23-1.el7.centos.x86_64 (mariadb-main)
>                mariadb-libs(x86-64) = 1:10.1.38-1.el7.centos
>            Available: MariaDB-compat-10.2.24-1.el7.centos.x86_64 (mariadb-main)
>                mariadb-libs(x86-64) = 1:10.1.38-1.el7.centos
>            Available: 1:mariadb100u-libs-10.0.34-1.ius.el7.x86_64 (ius)
>                mariadb-libs(x86-64) = 1:10.0.34-1.ius.el7
>            Available: 1:mariadb101u-libs-10.1.32-1.ius.el7.x86_64 (ius)
>                mariadb-libs(x86-64) = 1:10.1.32-1.ius.el7
>            Available: 1:mariadb101u-libs-10.1.35-1.ius.el7.x86_64 (ius)
>                mariadb-libs(x86-64) = 1:10.1.35-1.ius.el7
> Error: Package: 3:mariadb102-common-10.2.24-1.el7.ius.x86_64 (@ius)
>            Requires: mariadb-libs(x86-64) < 1:10
>            Removing: 1:mariadb-libs-5.5.60-1.el7_5.x86_64 (@base)
>                mariadb-libs(x86-64) = 1:5.5.60-1.el7_5
>            Obsoleted By: MariaDB-compat-10.2.25-1.el7.centos.x86_64 (mariadb-main)
>                mariadb-libs(x86-64) = 1:10.1.38-1.el7.centos
>            Available: MariaDB-compat-10.2.23-1.el7.centos.x86_64 (mariadb-main)
>                mariadb-libs(x86-64) = 1:10.1.38-1.el7.centos
>            Available: MariaDB-compat-10.2.24-1.el7.centos.x86_64 (mariadb-main)
>                mariadb-libs(x86-64) = 1:10.1.38-1.el7.centos
>            Available: 1:mariadb100u-libs-10.0.34-1.ius.el7.x86_64 (ius)
>                mariadb-libs(x86-64) = 1:10.0.34-1.ius.el7
>            Available: 1:mariadb101u-libs-10.1.32-1.ius.el7.x86_64 (ius)
>                mariadb-libs(x86-64) = 1:10.1.32-1.ius.el7
>            Available: 1:mariadb101u-libs-10.1.35-1.ius.el7.x86_64 (ius)
>                mariadb-libs(x86-64) = 1:10.1.35-1.ius.el7
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest

**Comment by carlwgeorge** [comment]
> `--exclude=mariadb-libs`

Why?  mariadb102 is [designed to work with stock mariadb-libs](https://github.com/iusrepo/mariadb102/wiki#implementation).  As you can see in your `rpm -qa` output, it's already installed.

> `---> Package MariaDB-compat.x86_64 0:10.2.25-1.el7.centos will be obsoleting`

MariaDB-compat is a package from the mariadb.org repos, so it appears that is enabled on your system.  Mixing that with IUS will give you unexpected results like this.  I suggest disabling that repo and sticking with just IUS.

As this is not an issue with the mariadb102 package, I'm going to close out this issue.  Feel free to stop by `#ius` or `#centos` on freenode for more general support.
